image: python:3.5

all_tests:
  script:
   - virtualenv -p python3 tmb-test
   - source tmb-test/bin/activate
   - pip install --upgrade pip
   - pip install -r requirements.txt
   - mv trackmybank/local_settings.py.test trackmybank/local_settings.py
   - python3 manage.py migrate
   - python3 manage.py collectstatic
   - python3 manage.py test -k
  when: on_success
