# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
                ('color', models.CharField(max_length=50, verbose_name='color')),
                ('is_goodies', models.BooleanField(verbose_name='Is goodies?')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20, verbose_name='month')),
                ('year', models.IntegerField(max_length=4, verbose_name='year')),
            ],
            options={
                'verbose_name': 'Month',
                'verbose_name_plural': 'Months',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_t', models.DateTimeField(verbose_name='transaction date')),
                ('date_bank', models.DateTimeField(null=True, verbose_name='bank added date')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category', verbose_name='category')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Month', verbose_name='month')),
            ],
        ),
    ]
