# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-16 18:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
                ('color', models.CharField(max_length=50, verbose_name='couleur')),
                ('is_goodies', models.BooleanField(verbose_name='Goodies ?')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='CurrentMonth',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='mois')),
                ('year', models.IntegerField(verbose_name='année')),
                ('salary', models.FloatField(verbose_name='salary')),
            ],
            options={
                'verbose_name': 'Mois',
                'verbose_name_plural': 'Mois',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='sujet')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='montant')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category', verbose_name='catégorie')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='TransactionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_t', models.DateField(verbose_name='date de la transaction')),
                ('date_bank', models.DateField(blank=True, null=True, verbose_name='date relevé bancaire')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Month', verbose_name='mois')),
            ],
            options={
                'verbose_name': 'Transaction group',
                'verbose_name_plural': 'Transaction groups',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TransactionGroup', verbose_name='groupe'),
        ),
        migrations.AddField(
            model_name='currentmonth',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Month', verbose_name='mois'),
        ),
    ]
