# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactiongroup',
            options={'verbose_name': 'Groupe de transactions', 'verbose_name_plural': 'Groupes de transactions'},
        ),
        migrations.AlterField(
            model_name='month',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TransactionGroup', verbose_name='Groupe'),
        ),
    ]
