# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='year',
            field=models.IntegerField(verbose_name='year'),
        ),
    ]
