# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 18:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('main', '0002_auto_20180918_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringCharges',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('file', models.CharField(max_length=1000, verbose_name='Chemin vers le fichier')),
            ],
        ),
    ]
