# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180911_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='month',
            options={'verbose_name': 'Mois', 'verbose_name_plural': 'Mois'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(max_length=50, verbose_name='couleur'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_goodies',
            field=models.BooleanField(verbose_name='Goodies ?'),
        ),
        migrations.AlterField(
            model_name='month',
            name='month',
            field=models.CharField(max_length=20, verbose_name='mois'),
        ),
        migrations.AlterField(
            model_name='month',
            name='year',
            field=models.IntegerField(verbose_name='année'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category', verbose_name='catégorie'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_bank',
            field=models.DateField(null=True, verbose_name='date relevé bancaire'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_t',
            field=models.DateField(verbose_name='date de la transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Month', verbose_name='mois'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='sujet'),
        ),
    ]
