# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-07 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_recurringcharges'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiongroup',
            name='ignore_week_filters',
            field=models.BooleanField(default=False, verbose_name='ignore weekly spending filters'),
        ),
        migrations.AlterField(
            model_name='recurringcharges',
            name='file',
            field=models.CharField(max_length=1000, verbose_name='Chemin du fichier'),
        ),
    ]
