# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180911_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_bank',
            field=models.DateField(blank=True, verbose_name='date relevé bancaire'),
        ),
    ]
