# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-07 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181007_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ignore_week_filters',
            field=models.BooleanField(default=False, verbose_name='ignorer les filtres de dépense par semaine'),
        ),
        migrations.AlterField(
            model_name='transactiongroup',
            name='ignore_week_filters',
            field=models.BooleanField(default=False, verbose_name='ignorer les filtres de dépense par semaine'),
        ),
    ]
