# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-03 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181007_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_saving',
            field=models.BooleanField(default=False, verbose_name='Is saving?'),
        ),
    ]
