# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180911_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=10, verbose_name='amount'),
            preserve_default=False,
        ),
    ]
