# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-01 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_category_is_saving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_saving',
            field=models.BooleanField(default=False, verbose_name='Économies ?'),
        ),
        migrations.AlterUniqueTogether(
            name='month',
            unique_together=set([('month', 'year')]),
        ),
    ]
