# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-01 16:32
from __future__ import unicode_literals

from django.db import migrations


def add_roles(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Role = apps.get_model("main", "Role")
    role1 = Role()
    role1.id = 1
    role1.name = "Website user"
    role1.save()
    role2 = Role()
    role2.id = 2
    role2.name = "API user"
    role2.save()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('main', '0008_auto_20190101_1732'),
    ]

    operations = [
        migrations.RunPython(add_roles)
    ]
