# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-16 15:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('main', '0008_month_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentMonth',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Month', verbose_name='mois')),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='montant'),
        ),
    ]
