# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-06 12:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_default_group(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Group = apps.get_model("main", "Group")
    group = Group()
    group.id = 1
    group.name = "Default"
    group.save()
    User = apps.get_model("auth", "User")
    UserGroup = apps.get_model("main", "UserGroup")
    for user in User.objects.all():
        user_group = UserGroup(user=user, group=group)
        user_group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('main', '0009_auto_20190101_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=20, verbose_name='Group')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'User group',
            },
        ),
        migrations.RunPython(add_default_group),
        migrations.RemoveField(
            model_name='currentmonth',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recurringcharges',
            name='user',
        ),
        migrations.AddField(
            model_name='currentmonth',
            name='group',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurringcharges',
            name='group',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.Group'),
            preserve_default=False,
        ),
    ]
