# Generated by Django 2.2.3 on 2019-07-28 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_month_ugroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Groupe', 'verbose_name_plural': 'Groupes'},
        ),
        migrations.AlterModelOptions(
            name='recurringcharges',
            options={'verbose_name': 'Charges récurrentes', 'verbose_name_plural': 'Charges récurrentes'},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name': 'Groupe utilisateur', 'verbose_name_plural': 'Groupes utilisateur'},
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Groupe'),
        ),
        migrations.AlterField(
            model_name='month',
            name='ugroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Group', verbose_name="groupe de l'utilisateur"),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Group', verbose_name='Groupe'),
        ),
    ]
